export const roleMap: { [key: string]: string } = {
  "Fighter": "Luchador",
  "Assassin": "Asesino",
  "Mage": "Mago",
  "Marksman": "Tirador",
  "Support": "Soporte",
  "Tank": "Tanque",
};



export const regionMap: { [key: string]: string } = {
  "Aatrox": "Runaterra",
  "Ahri": "Ionia",
  "Akali": "Ionia",
  "Akshan": "Shurima",
  "Alistar": "Demacia",
  "Amumu": "Shurima",
  "Anivia": "Freljord",
  "Annie": "Freljord",
  "Aphelios": "Ixtal",
  "Aurelion Sol": "Targon",
  "Azira": "Shurima",
  "Bard": "Shurima",
  "Bel'Veth": "Vacío",
  "Blitzcrank": "Zaun",
  "Brand": "Freljord",
  "Briar": "Ixtal",
  "Braum": "Freljord",
  "Camille": "Piltover",
  "Cassiopeia": "Shurima",
  "Chogath": "Vacío",
  "Corki": "Ciudad Bandle",
  "Darius": "Noxus",
  "Diana": "Targon",
  "Dr. Mundo": "Zaun",
  "Draven": "Noxus",
  "Ekko": "Zaun",
  "Elise": "Noxus",
  "Evelynn": "Ionia",
  "Ezreal": "Piltover",
  "Fiora": "Demacia",
  "Fizz": "Ionia",
  "Galio": "Demacia",
  "Gangplank": "Aguasturbias",
  "Garen": "Demacia",
  "Gnar": "Freljord",
  "Gragas": "Freljord",
  "Graves": "Aguasturbias",
  "Hecarim": "Islas Sombrías",
  "Heimerdinger": "Piltover",
  "Illaoi": "Targon",
  "Irelia": "Ionia",
  "Janna": "Ionia",
  "Jarvan IV": "Demacia",
  "Jhin": "Ionia",
  "Jinx": "Piltover",
  "Kalista": "Islas Sombrías",
  "Karma": "Ionia",
  "Kayn": "Islas Sombrías",
  "Karthus": "Islas Sombrías",
  "Kassadin": "Shurima",
  "Katarina": "Noxus",
  "Kayle": "Demacia",
  "Kennen": "Ionia",
  "Kha'Zix": "Vacío",
  "Kindred": "Runaterra",
  "K'Sante": "Shurima",
  "Kled": "Noxus",
  "Kog'Maw": "Vacío",
  "LeBlanc": "Noxus",
  "Lee Sin": "Ionia",
  "Leona": "Targon",
  "Lillia": "Ionia",
  "Lissandra": "Freljord",
  "Lux": "Demacia",
  "Malphite": "Shurima",
  "Malzahar": "Vacío",
  "Maokai": "Islas Sombrías",
  "Milio": "Ixtal",
  "Miss Fortune": "Aguasturbias",
  "Monkey King": "Ionia",
  "Mordekaiser": "Noxus",
  "Nami": "Ionia",
  "Nasus": "Shurima",
  "Nidalee": "Shurima",
  "Nilah": "Ixtal",
  "Nunu y Willump": "Freljord",
  "Nocturne": "Islas Sombrías",
  "Olaf": "Freljord",
  "Orianna": "Piltover",
  "Pantheon": "Targon",
  "Poppy": "Demacia",
  "Pyke": "Aguasturbias",
  "Qiyana": "Ixtal",
  "Quinn": "Demacia",
  "Rell": "Noxus",
  "Renata Glasc": "Zaun",
  "Rengar": "Shurima",
  "Riven": "Noxus",
  "Rumble": "Ciudad Bandle",
  "Ryze": "Runaterra",
  "Samira": "Noxus",
  "Sejuani": "Freljord",
  "Senna": "Islas Sombrías",
  "Seraphine": "Piltover",
  "Shaco": "Noxus",
  "Shen": "Ionia",
  "Shyvana": "Shurima",
  "Sivir": "Shurima",
  "Sona": "Demacia",
  "Soraka": "Targon",
  "Swain": "Noxus",
  "Sylas": "Demacia",
  "Syndra": "Ionia",
  "Talon": "Noxus",
  "Teemo": "Ciudad Bandle",
  "Thresh": "Islas Sombrías",
  "Tristana": "Ciudad Bandle",
  "Trundle": "Freljord",
  "Tryndamere": "Freljord",
  "Twisted Fate": "Aguasturbias",
  "Twitch": "Zaun",
  "Udyr": "Freljord",
  "Urgot": "Noxus",
  "Vayne": "Demacia",
  "Vel'Koz": "Vacío",
  "Vex": "Aguasturbias",
  "Viego": "Islas Sombrías",
  "Viktor": "Zaun",
  "Vladimir": "Noxus",
  "Volibear": "Freljord",
  "Warwick": "Zaun",
  "Wukong": "Ionia",
  "Xayah": "Ionia",
  "Xerath": "Shurima",
  "Xin Zhao": "Ixtal",
  "Yasuo": "Ionia",
  "Yone": "Ionia",
  "Yuumi": "Ciudad Bandle",
  "Zac": "Zaun",
  "Zed": "Ionia",
  "Zeri": "Zaun",
  "Ziggs": "Piltover",
  "Zilean": "Targon",
  "Zoe": "Ionia",
  "Zyra": "Ixtal",
  "Bardo": "Runaterra",
  "Ashe": "Freljord",
  "Azir": "Shurima",
  "Cho'Gath": "Vacío",
  "Caitlyn": "Piltover",
  "Fiddlesticks": "Ixtal",
  "Gwen": "Ionia",
  "Ivern": "Ionia",
  "Jax": "Ixtal",
  "Jayce": "Piltover",
  "Kai'Sa": "Vacío",
  "Lucian": "Demacia",
  "Lulu": "Ionia",
  "Maestro Yi": "Ionia",
  "Morgana": "Demacia",
  "Naafiri": "Shurima",
  "Nautilus": "Aguasturbias",
  "Neeko": "Ixtal",
  "Ornn": "Freljord",
  "Rakan": "Ionia",
  "Rammus": "Shurima",
  "Renekton": "Shurima",
  "Sett": "Ionia",
  "Singed": "Zaun",
  "Sion": "Freljord",
  "Skarner": "Shurima",
  "Tahm Kench": "Aguasturbias",
  "Taliyah": "Shurima",
  "Taric": "Demacia",
  "Varus": "Freljord",
  "Veigar": "Aguasturbias",
  "Vi": "Piltover",
  "Yorick": "Islas Sombrías",
  "Rek'Sai": "Vacío"
};
